# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: chaps build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test on python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.5', '3.6', '3.7', '3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_verion }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 nose
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pwd
        mkdir ~/bin
        (cd ~/bin;\
        wget --no-check-certificate "https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz";
        tar Jxvf ffmpeg-release-amd64-static.tar.xz)
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 .
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with nosetests
      run: |
        PATH=$PATH:~/bin/ffmpeg-4.2.3-amd64-static
        export PATH=$PATH:~/bin/ffmpeg-4.2.3-amd64-static
        nosetests --with-coverage --cover-package=chapter_split --cover-html --cover-erase --cover-branches --verbose test
